# Generated by Django 3.2.12 on 2022-04-26 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_news_app', '0021_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(default='Hot News', max_length=100)),
                ('article', models.TextField()),
                ('image', models.FileField(default=None, upload_to='images/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('article_permission', models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default='public', max_length=35)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
